name: Run Robot Framework UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdrivermanager
          webdrivermanager chrome --linkpath /usr/local/bin

      - name: Start web server
        run: |
          ./mvnw spring-boot:run &
          sleep 20

      - name: Run Robot Framework tests
        run: |
          robot tests/

      - name: Upload Robot test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: |
            log.html
            output.xml
            report.html
