name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework selenium webdriver-manager

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Robot Framework Tests
        run: |
          robot tests/

      - name: Upload Robot Test Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: |
            log.html
            output.xml
            report.html
